### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by WangJunTYTL** [WangJunTYTL/perf4j-zh#2]
### dashboard 前端功能
1. 左侧机器列表可以支持按集群进行折叠
2. 集群机器的配置可以通过页面表单提交的方式并可以把信息保存到sqlite中
3. 可以在上部导航栏右侧自定义链接
### perf4j
1. SqliteAppend可以支持logback
2. jvm监控信息下面也可以显示基本的OS的信息：CPU、Memory、Load

**Comment by awoter** [comment]
只看到有用ES保存数据，没看到从ES读取及展示图表。请问下楼主，这块可有开发？

**Comment by WangJunTYTL** [comment]
没有计划开发图标渲染  Grafana在图表渲染领域做的很棒了 非常推荐使用Grafana  支持ES数据源及常见的其它数据源
